# Generated by Django 3.1.7 on 2021-04-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_mistri_app', '0007_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
