# Generated by Django 3.1.7 on 2021-04-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_mistri_app', '0015_clientinformation_mistriinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
