# Generated by Django 3.1.7 on 2021-04-08 14:50

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hello_mistri_app', '0017_auto_20210408_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Clint_UID',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mistri_UID',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MistriInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mistri_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('phone', phone_field.models.PhoneField(help_text='Contact phone number', max_length=31)),
                ('image', models.ImageField(upload_to='media')),
                ('dob', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('mistri_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_mistri_app.mistri_uid')),
            ],
        ),
        migrations.CreateModel(
            name='ClientInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clint_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('phone', phone_field.models.PhoneField(help_text='Contact phone number', max_length=31)),
                ('address', models.CharField(max_length=500)),
                ('clint_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_mistri_app.clint_uid')),
            ],
        ),
    ]
