# Generated by Django 3.1.7 on 2021-04-22 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello_mistri_app', '0069_clientinformation_mistriinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_area_name', models.CharField(max_length=100)),
                ('area_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hello_mistri_app.area')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='city_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hello_mistri_app.city'),
        ),
    ]
