# Generated by Django 3.1.7 on 2021-04-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_mistri_app', '0089_auto_20210428_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinformation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mistriinformation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subarea',
            name='area_name',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='ClientInformation',
        ),
        migrations.DeleteModel(
            name='MistriInformation',
        ),
        migrations.DeleteModel(
            name='SubArea',
        ),
    ]
