# Generated by Django 3.1.7 on 2021-05-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_mistri_app', '0098_auto_20210512_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinformation',
            name='address',
        ),
    ]
