# Generated by Django 3.1.7 on 2021-07-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_mistri_app', '0112_auto_20210616_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersubmitbyclient',
            name='discount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordersubmitbyclient',
            name='mistri_name',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='ordersubmitbyclient',
            name='mistri_uid',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
