# Generated by Django 3.1.7 on 2021-07-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_mistri_app', '0113_auto_20210709_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersubmitbyclient',
            name='order_holder_uid',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
